"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { SectionHeading } from "@/components/site/sections";

const QUESTIONS = [
  {
    q: "Are the recipes actually any good?",
    a: "They're generated by a language model, so judge them the way you'd judge a recipe from a stranger: the technique is usually sound, the timings are usually right, and you should still taste as you go. Every recipe tells you which model wrote it. If one is wrong, the fastest fix is to tell it what went wrong and regenerate.",
  },
  {
    q: "Can I trust it with a serious allergy?",
    a: "Dietary requirements are enforced as hard constraints in the prompt, and a recipe that violates one is treated as a failure rather than a near miss. That said: this is software, and the stakes with a severe allergy are not ours to accept on your behalf. Read the ingredient list before you cook. We would say the same about a cookbook.",
  },
  {
    q: "How does the photo scanning work?",
    a: "You photograph an open fridge or cupboard and the image goes to a vision model, which lists what it can see. Anything it isn't confident about is shown separately for you to confirm rather than added silently — a wrong ingredient quietly poisons every suggestion that follows. Photos are used for that one request and not kept.",
  },
  {
    q: "Is the pet food safe?",
    a: "The toxic-ingredient list is enforced as a rule, not left to the model's judgement, and cats are always treated as obligate carnivores. But home-cooked pet food is genuinely not nutritionally complete without supplementation, and every recipe says so. Use it as a topper, or take the recipe to your vet before it becomes a staple.",
  },
  {
    q: "What happens when the free plan runs out?",
    a: "The free plan is three generations a day. It resets at midnight UTC. Everything you already generated stays yours, and you keep the pantry, the saved recipes, and both leftovers and appliance modes. Photo scanning, meal plans, and PantryPup are the paid features.",
  },
  {
    q: "Do I need a subscription to buy a cookbook?",
    a: "No. Cookbooks are one-off purchases and work on a free account. Household subscribers get 20% off them.",
  },
  {
    q: "Can I cancel whenever I want?",
    a: "Any time, from the billing page, through Stripe's own portal. You keep paid features until the end of the period you've already paid for, then drop to free. Nothing is deleted.",
  },
];

export function Faq() {
  return (
    <section className="band bg-surface-muted">
      <div className="shell">
        <SectionHeading title="Reasonable questions" />

        <div className="mt-12 max-w-3xl">
          <Accordion type="multiple" className="divide-y divide-hairline border-y border-hairline">
            {QUESTIONS.map((item, i) => (
              <AccordionItem key={item.q} value={`item-${i}`} className="border-none">
                <AccordionTrigger className="py-6 text-left text-medium font-semibold tracking-tight text-ink hover:no-underline md:text-h6">
                  {item.q}
                </AccordionTrigger>
                <AccordionContent className="pb-6 pr-8 text-regular text-pretty text-ink-soft">
                  {item.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
